-- AlterTable
ALTER TABLE "User" ALTER COLUMN "bMonth" DROP DEFAULT,
ALTER COLUMN "bYear" DROP DEFAULT,
ALTER COLUMN "filter" SET DEFAULT false,
ALTER COLUMN "profileImg" DROP NOT NULL,
ALTER COLUMN "profileImg" DROP DEFAULT,
ALTER COLUMN "bio" SET DEFAULT 'test';
